[package]
name = "spaced-list-5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"num-traits" = "0.2.14"

[dev-dependencies]
"rand" = "0.8.5"

[profile.test]
#"opt-level" = 3